[FIX] 계획블록 삭제하기 Service 로직 API
Team-DragMe/DragMe-Server pull request #71
Opened 2022-07-18 18:18 UTC by m1njae

## Solved Issue
close #70 

<br>

## Motivation
- 하위 계획블록만 삭제하는 것을 구현해놓지 않은 상태입니다.

<br>

## Key Changes
- Service 로직 수정

<br>

## To Reviewers
- Schedule Collection에 있는 상위 계획과 하위 계획을 구별하는 로직이 필요했습니다!
- 코드를 짜다보니까 구현은 되는데 코드 자체가 깔끔하지 못한 것 같다는 느낌이 들었습니다.
- 확인해주시고, 혹시 수정할 부분이 있으면 가감없이 피드백 남겨주시면 감사하겠습니당!

2022-07-18 18:39 UTC, HYOSITIVE commented on src/services/ScheduleService.ts
> +          subSchedules: scheduleId,
subSchedules는 배열이고 scheduleId는 배열의 하나의 원소일텐데 이렇게 하면 바로 찾아지나요? 신기하다

2022-07-18 18:40 UTC, HYOSITIVE approved these changes
크 베리굿 성장하는게 보이는구만~ 고생했다!

2022-07-18 18:41 UTC, m1njae commented on src/services/ScheduleService.ts
> +          subSchedules: scheduleId,
생각해보니까 여러 개를 안넣고 해봤네욥ㅋㅋㅋ 이따가 테스트 다시 해보겠읍니당

2022-07-18 19:22 UTC, m1njae commented on src/services/ScheduleService.ts
> +          subSchedules: scheduleId,
테스트 결과 되네욥! 몽고반점 자식 알다가도 모르겠어~

2022-07-18 19:26 UTC, m1njae commented
근데 세미나에서 `delete`는 request body를 받지 않는다고 학습해서  scheduleId를 query에 받는 건 어떨까라는 생각이 문득 들었는데 어떤가요? 내일 출근하셔서 확인 부탁드려용~ 오늘 너무 고생 많이 했어 효식아👍

2022-07-19 05:16 UTC, HYOSITIVE commented
> 근데 세미나에서 `delete`는 request body를 받지 않는다고 학습해서 scheduleId를 query에 받는 건 어떨까라는 생각이 문득 들었는데 어떤가요? 내일 출근하셔서 확인 부탁드려용~ 오늘 너무 고생 많이 했어 효식아👍

post나 patch처럼 여러 정보를 받는게 아니라 삭제할 자원을 식별하기 위한거라면 query가 나을 것 같아요~

2022-07-19 05:57 UTC, m1njae commented
query로 수정해서 주석도 변경했는데 한번만 더 확인 부탁드립니다..! 고생하십니당!

2022-07-19 06:02 UTC, HYOSITIVE requested changes

2022-07-19 06:02 UTC, HYOSITIVE commented on src/controllers/ScheduleController.ts
>   */
이거 왜 두개됨...?

2022-07-19 06:03 UTC, HYOSITIVE commented on src/controllers/ScheduleController.ts
>   */
어 뭐냐 아까 오류였나 이제 제대로 나오네

2022-07-19 06:03 UTC, HYOSITIVE approved these changes

2022-07-19 06:03 UTC, m1njae commented on src/controllers/ScheduleController.ts
>   */
@route가 두 개 되었냐는 말인가여?

2022-07-19 06:05 UTC, HYOSITIVE commented on src/controllers/ScheduleController.ts
>   */
아니 저게 아까 route가 사라지고 const = async 이게 두줄로 보였어...

2022-07-19 06:05 UTC, merged